# Production environment configuration

# Inherit from base configuration
extends: "base"

# Override settings for production
trading:
  modes:
    production:
      live_trading: true

# Database settings for production
database:
  host: "localhost"
  port: 5432
  name: "trading_system_prod"
  user: "trader_prod"
  # Password should be in keyring or environment variables

# Web interface settings for production
web:
  host: "0.0.0.0"
  port: 8000
  debug: false

# Risk management (strict for production)
risk:
  max_capital_per_trade: 0.01  # 1% of equity
  max_concurrent_trades: 10
  daily_loss_limit: 0.02  # 2% of equity
  single_name_exposure_limit: 0.05  # 5% of equity