# Stock Suggestions Display Configuration
# DEPRECATED: This config is no longer used after migration to pure 8-21 EMA strategy.
# The system now uses EMA-based filtering directly without ML model types.
# Kept for historical reference only.
#
# Industry-standard thresholds for displaying suggested stocks to users in the UI
# This is separate from stock_filters.yaml which is used during the discovery pipeline
# All parameters are configurable - adjust based on market conditions and strategy

# ===========================
# MODEL SELECTION CRITERIA
# ===========================
model_selection:
  # Which models to show predictions from
  enabled_models:
    - traditional  # Random Forest + XGBoost ensemble
    - raw_lstm     # Deep learning OHLCV sequences
    - kronos       # K-line tokenization foundation model

  # Per-model minimum score thresholds (0.0 to 1.0)
  # Industry standard: 0.60+ for Buy signals, 0.50-0.60 for moderate confidence
  # NOTE: Adjusted to match actual ML model output
  minimum_scores:
    traditional: 0.50    # Adjusted: actual scores 0.5614-0.6493
    raw_lstm: 0.45       # Adjusted: actual scores all 0.5000
    kronos: 0.50         # Adjusted: actual scores 0.3823-0.9676

  # Recommendation filtering
  allowed_recommendations:
    - BUY              # Only show actionable buy signals
    # - STRONG_BUY     # Uncomment if your models generate this
    # - HOLD           # Uncomment to include hold recommendations

  # Confidence thresholds (0.0 to 1.0)
  # Industry standard: 0.60+ for high confidence, 0.50-0.60 for moderate
  # NOTE: Adjusted to match actual ML model output (traditional: 0.19-0.22, raw_lstm: 0.0)
  minimum_confidence:
    default_risk: 0.15   # Adjusted to match actual traditional ML output (0.19-0.22)
    high_risk: 0.10      # Adjusted to allow aggressive picks with lower confidence

# ===========================
# PRICE & VALUATION FILTERS
# ===========================
valuation:
  # Upside potential (positive expected return)
  minimum_upside_pct: 2.0      # Min 2% upside from current price to target
  maximum_upside_pct: 50.0     # Max 50% upside (filter outliers)

  # Price-to-Earnings (P/E) ratio
  pe_ratio:
    minimum: 5.0               # Avoid value traps (too low PE)
    maximum: 40.0              # Industry standard for growth stocks
    allow_null: true           # Include stocks without P/E data

  # Price-to-Book (P/B) ratio
  pb_ratio:
    minimum: 0.5               # Below 0.5 might indicate distress
    maximum: 10.0              # Above 10 might be overvalued
    allow_null: true

  # Return on Equity (ROE %)
  roe:
    minimum: 10.0              # Industry standard: 10%+ for healthy companies
    maximum: 50.0              # Cap at 50% (filter anomalies)
    allow_null: true

# ===========================
# RISK MANAGEMENT
# ===========================
risk:
  # ML Risk Score (0.0 = low risk, 1.0 = high risk)
  maximum_risk_score: 0.40     # Industry standard: keep risk under 40%

  # Stop loss validation
  require_stop_loss: true      # Must have defined stop loss
  minimum_stop_loss_pct: 2.0   # Stop loss at least 2% below entry
  maximum_stop_loss_pct: 10.0  # Stop loss max 10% below entry

  # Risk-reward ratio
  minimum_risk_reward_ratio: 1.5  # Target gain should be 1.5x potential loss

# ===========================
# MARKET CAP & LIQUIDITY
# ===========================
liquidity:
  # Market cap categories (in Crores)
  default_risk:
    minimum_market_cap: 5000    # 5000 Cr = Large/Mid cap for conservative
    preferred_categories:
      - large_cap
      - mid_cap

  high_risk:
    minimum_market_cap: 1000    # 1000 Cr = Small/Mid cap for aggressive
    preferred_categories:
      - mid_cap
      - small_cap

  # Daily trading requirements
  minimum_daily_volume: 50000           # Min 50k shares traded
  minimum_daily_turnover_cr: 5.0        # Min ₹5 Cr daily turnover

# ===========================
# DISPLAY & SORTING
# ===========================
display:
  # Default limits per model/strategy combination
  default_limit: 10              # Show top 10 stocks per tab
  maximum_limit: 50              # Max allowed via API parameter

  # Sorting preference
  sort_by: ml_prediction_score   # Primary sort field
  sort_order: desc               # Descending (highest scores first)

  # Secondary sort (tie-breaker)
  secondary_sort:
    - ml_confidence              # Higher confidence wins
    - upside_percentage          # Higher upside wins

  # Display filters
  show_zero_upside: false        # Hide stocks with no positive upside
  show_below_current_price: false # Hide stocks trading above target

# ===========================
# STRATEGY-SPECIFIC RULES
# ===========================
strategies:
  DEFAULT_RISK:
    name: "Conservative Strategy"
    description: "Large-cap stocks with stable growth"
    target_gain_pct: 5.0 - 7.0
    stop_loss_pct: 3.0
    holding_period_days: 14
    min_ml_score: 0.58           # Higher bar for conservative

  HIGH_RISK:
    name: "Aggressive Strategy"
    description: "Small/Mid-cap stocks with high growth potential"
    target_gain_pct: 8.0 - 12.0
    stop_loss_pct: 5.0
    holding_period_days: 21
    min_ml_score: 0.52           # Lower bar for aggressive

# ===========================
# DATA QUALITY
# ===========================
data_quality:
  # Freshness requirements
  maximum_data_age_days: 7       # Only show predictions from last 7 days
  require_current_price: true    # Must have valid current price
  require_ml_target: true        # Must have ML price target

  # Field validation
  required_fields:
    - symbol
    - model_type
    - strategy
    - ml_prediction_score
    - ml_price_target
    - current_price
    - recommendation

  # Outlier detection
  remove_outliers: true
  outlier_z_score_threshold: 3.0  # Remove predictions > 3 std devs

# ===========================
# CACHING & PERFORMANCE
# ===========================
cache:
  enable_caching: true
  cache_duration_seconds: 300    # 5 minutes
  cache_key_prefix: "stock_suggestions_"

# ===========================
# LOGGING & MONITORING
# ===========================
logging:
  log_filtered_count: true       # Log how many stocks were filtered out
  log_filter_reasons: true       # Log why stocks were filtered
  log_performance_metrics: true  # Log query performance

  # Alert thresholds
  alert_if_zero_results: true    # Alert if no stocks pass filters
  alert_if_below_minimum: true   # Alert if < 3 stocks per strategy
  minimum_stocks_per_strategy: 3

# ===========================
# FEATURE FLAGS
# ===========================
features:
  enable_score_normalization: true     # Normalize scores across models
  enable_sector_diversification: true  # Prefer diverse sectors
  enable_correlation_filter: false     # Filter highly correlated stocks
  enable_sentiment_boost: false        # Boost based on news sentiment

  # Experimental features
  experimental:
    enable_ensemble_scoring: false     # Combine multiple model scores
    enable_dynamic_thresholds: false   # Adjust thresholds based on market
    enable_regime_detection: false     # Adjust for bull/bear markets
