# Unified configuration for the trading system

# Inherit from base configuration
extends: "base"

# System settings
system:
  log_level: "DEBUG"

# Trading settings
trading:
  # Market timings (IST)
  market_open: "09:15"
  market_close: "15:30"
  pre_open_start: "09:00"
  pre_open_end: "09:15"
  
  # Trading modes
  modes:
    development:
      description: "Paper trading simulation mode"
      live_trading: false
    production:
      description: "Live trading mode"
      live_trading: true

# Risk management defaults
risk:
  max_capital_per_trade: 0.01  # 1% of equity
  max_concurrent_trades: 10
  daily_loss_limit: 0.02  # 2% of equity
  single_name_exposure_limit: 0.05  # 5% of equity

# Momentum strategy defaults
momentum:
  universe: "NIFTY_100"
  rebalance_cadence: "daily"
  lookback_period: 20  # days
  min_volume_filter: 100000  # minimum daily volume

# Database settings
database:
  host: "database"  # Docker service name
  port: 5432
  name: "trading_system"
  user: "trader"
  password: "trader_password"

# Email settings
email:
  smtp_host: "smtp.gmail.com"
  smtp_port: 587
  use_tls: true
  # Credentials should be in environment-specific config or keyring

# Web interface
web:
  host: "0.0.0.0"
  port: 5001
  debug: true